# Generated by Django 5.0.2 on 2024-03-04 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file1", models.FileField(upload_to="fichiers/")),
                ("file2", models.FileField(upload_to="fichiers/")),
                ("file3", models.FileField(upload_to="fichiers/")),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes/")),
            ],
        ),
    ]
