# Generated by Django 5.0.2 on 2024-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
    ]
