# Generated by Django 5.0.2 on 2024-03-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_alter_client_file1_alter_client_file2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="qr_code",
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="qr_codes/")),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="client.client",
                    ),
                ),
            ],
        ),
    ]
