# Generated by Django 5.0.2 on 2024-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_file2_remove_client_file3'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Seq_nr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
