# Generated by Django 5.0.2 on 2024-03-04 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ask", models.TextField(max_length=360)),
                ("description", models.TextField(max_length=4000)),
                ("show", models.BooleanField()),
            ],
        ),
    ]
