# Generated by Django 5.0.2 on 2024-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super", "0002_ask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
