# Generated by Django 5.0.2 on 2024-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super", "0003_alter_product_description_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
